[target.arm-unknown-linux-musleabihf]
linker = "/home/david/.local/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "/home/david/.local/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.mipsel-unknown-linux-musl]
linker = "/home/david/pi-glass/mips-ld-wrapper.sh"
rustflags = ["-C", "panic=abort", "-C", "opt-level=s", "-C", "target-feature=+crt-static"]
